---
- name: Install lighttpd
  apt:
    pkg:
      - lighttpd

- name: Create lighttpd webroot dirs
  file:
    path: '{{ "" if (item.value.root[0] == "/") else (lighttpd_webroot + "/") }}{{ item.value.root }}'
    state: directory
    owner: '{{ lighttpd_user }}'
    group: '{{ lighttpd_group }}'
    mode: '2775'
  with_dict: '{{ lighttpd.domains | default({}) }}'
  when: item.value is defined

- name: Add {{ user }} to {{ lighttpd_group }} group
  user:
    name: '{{ user }}'
    groups:
      - '{{ lighttpd_group }}'
    append: true

- include_tasks:
    file: lighttpd-write-config.yml
    apply:
      tags:
        - server

- name: Create lighttpd password file
  file:
    state: touch
    path: '{{ lighttpd_passwd_file }}'
    owner: root
    group: '{{ lighttpd_group }}'
    mode: '0640'

- name: Generate dhparam (this can take hours)
  command:
    cmd: 'openssl dhparam -out {{ dhparam_file }} 4096'
    creates: '{{ dhparam_file }}'

- name: Restart lighttpd
  service:
    name: lighttpd
    state: restarted
