---
- name: Install pelican
  pip:
    name:
      - pelican[Markdown]

- name: Install pelican themes
  git:
    repo: https://github.com/getpelican/pelican-themes.git
    dest: '{{ pelican_themes_dir }}'

- name: Compose pelican dir
  set_fact:
    output_dir: '{{ ("" if pelican_rel[0] == "/" else lighttpd_webroot + "/") + pelican_rel }}'
  vars:
    pelican_rel: '{{ lighttpd.domains[pelican.domain].root }}'

- name: Generate pelican config
  template:
    src: pelicanconf.py.j2
    dest: '{{ output_dir | dirname }}/pelicanconf.py'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'
    lstrip_blocks: True

- name: Create directories
  file:
    path: '{{ output_dir | dirname }}/{{ item }}'
  with_items:
    - content
    - file
    - '{{ pelican_custom_themes_dir }}'

- name: Generate blog script
  template:
    src: blog.j2
    dest: 'bin/blog'
    mode: '0775'
    lstrip_blocks: True
  become: False
