---
- include_tasks:
    file: '{{ _auto_task }}'
    apply:
      tags:
        - server
  loop: '{{ query("fileglob", "*.yml") | sort }}'
  loop_control:
    loop_var: _auto_task
  when:
    - _auto_task | regex_search('/[0-9]+-[-a-zA-Z_]+\.yml$')
    - "(_auto_task | regex_replace('^.*/[0-9]+-([-a-zA-Z_]+)\\\\.yml$', '\\\\1')) not in gated_tasks
      or lookup('vars', (_auto_task | regex_replace('^.*/[0-9]+-([-a-zA-Z_]+)\\\\.yml$', '\\\\1')), default=false)"
  tags:
    - always
    - server
